### ISSUE TITLE
Invert applyLogJetColorMap

### ISSUE THREAD

**Issue by drydenwiebe** [pat676/MLPDepthMap#1]
Hello!

I have found a (depth) dataset that has had applyLogJetColorMap (https://github.com/pat676/MLPDepthMap/blob/master/src/MLPDataInterpreter.py#L115) from this repository applied to it. I was wondering if you know of a way to invert this process?

Thanks!

**Comment by pat676** [comment]
Hi, 

Sorry, but I don’t know of any method for inverting this process. Maybe you could contact the authors of the dataset to get the original images? 

Best regards,
Patrick Henriksen.

**Comment by drydenwiebe** [comment]
Yeah, that is my best bet I think. 

Thank you for the response!
